data:
  data_train:
    data_path: "datasets/labeling_datasets/labeling_2.csv"

data_loader:
  train:
    pin_memory: True
    shuffle: True
    drop_last: True
    num_workers: 4
    batch_size: 64

  valid:
    pin_memory: True
    shuffle: False
    drop_last: False
    num_workers: 4
    batch_size: 64

  test:
    pin_memory: True
    shuffle: False
    drop_last: False
    num_workers: 4
    batch_size: 64

base:
  seed: 42
  text_max_length: 256